import {
  mdiCircleOutline,
  mdiVideo, mdiEye, mdiAccountPlus, mdiFlagOutline, mdiFlag,
  mdiThumbUp, mdiThumbDown, mdiComment, mdiClockOutline,
  mdiPencil, mdiDelete, mdiPlus, mdiMagnify, mdiCheck,
  mdiClose, mdiCloseCircle, mdiCheckCircle, mdiLock,
  mdiImage, mdiImagePlus, mdiVideoPlus, mdiContentSave,
  mdiPlay, mdiPlayCircle, mdiChartLine, mdiAccountCancel,
  mdiAccountCheck, mdiAccountKey, mdiAccountCircle,
  mdiEmail, mdiCloud, mdiEyeOff, mdiCheckDecagram,
  mdiCancel, mdiCamera, mdiCog, mdiShieldOutline,
  mdiShopping, mdiGraph, mdiChartBox,
  mdiHome, mdiLayers, mdiTag, mdiFolder, mdiFolderOpen,
  mdiMessage, mdiAccount, mdiChevronRight,
} from '@mdi/js';

export const icons = {
  circleOutline: mdiCircleOutline,
  video: mdiVideo,
  eye: mdiEye,
  'eye-off': mdiEyeOff,
  'account-plus': mdiAccountPlus,
  'flag-outline': mdiFlagOutline,
  flag: mdiFlag,
  'thumb-up': mdiThumbUp,
  'thumb-down': mdiThumbDown,
  comment: mdiComment,
  'clock-outline': mdiClockOutline,
  pencil: mdiPencil,
  delete: mdiDelete,
  plus: mdiPlus,
  magnify: mdiMagnify,
  check: mdiCheck,
  close: mdiClose,
  'close-circle': mdiCloseCircle,
  'check-circle': mdiCheckCircle,
  lock: mdiLock,
  image: mdiImage,
  'image-plus': mdiImagePlus,
  'video-plus': mdiVideoPlus,
  'content-save': mdiContentSave,
  play: mdiPlay,
  'play-circle': mdiPlayCircle,
  'chart-line': mdiChartLine,
  'account-cancel': mdiAccountCancel,
  'account-check': mdiAccountCheck,
  'account-key': mdiAccountKey,
  'account-circle': mdiAccountCircle,
  email: mdiEmail,
  cloud: mdiCloud,
  'check-decagram': mdiCheckDecagram,
  cancel: mdiCancel,
  'chevron-right': mdiChevronRight,
  home: mdiHome,
  layers: mdiLayers,
  tag: mdiTag,
  folder: mdiFolder,
  'folder-open': mdiFolderOpen,
  message: mdiMessage,
  account: mdiAccount,
  shopping: mdiShopping,
  graph: mdiGraph,
  'chart-box': mdiChartBox,
};
